# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 113)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(300, 113))
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.name_item = QtWidgets.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.name_item.setFont(font)
        self.name_item.setStyleSheet("QLineEdit{\n"
"    border:None;\n"
"    border-bottom: 2px solid rgb(0, 157, 255);\n"
"}")
        self.name_item.setObjectName("name_item")
        self.verticalLayout.addWidget(self.name_item)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"    text-align: right;\n"
"    margin-top: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(183, 228, 255);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: rgb(165, 165, 165);\n"
"    border-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.submit = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.submit.setFont(font)
        self.submit.setStyleSheet("QPushButton{\n"
"    text-align: right;\n"
"    margin-top: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(183, 228, 255);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: rgb(165, 165, 165);\n"
"    border-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.submit.setObjectName("submit")
        self.horizontalLayout.addWidget(self.submit)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Новый список"))
        self.label.setText(_translate("Form", "Новый список"))
        self.name_item.setPlaceholderText(_translate("Form", "Введите название списка"))
        self.cancel.setText(_translate("Form", "Отмена"))
        self.submit.setText(_translate("Form", "Создать список"))
