# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_task.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 131)
        Form.setMinimumSize(QtCore.QSize(300, 131))
        Form.setMaximumSize(QtCore.QSize(430, 131))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.task_line = QtWidgets.QLineEdit(Form)
        self.task_line.setStyleSheet("QLineEdit{\n"
"    border:None;\n"
"    border-bottom: 2px solid rgb(0, 157, 255);\n"
"}")
        self.task_line.setObjectName("task_line")
        self.verticalLayout.addWidget(self.task_line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.date = QtWidgets.QDateTimeEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setStyleSheet("QDateTimeEdit{\n"
"    border:None;\n"
"}")
        self.date.setObjectName("date")
        self.horizontalLayout_2.addWidget(self.date)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancel = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet("QPushButton{\n"
"    text-align: right;\n"
"    margin-top: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(183, 228, 255);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: rgb(165, 165, 165);\n"
"    border-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        self.add = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.add.setFont(font)
        self.add.setStyleSheet("QPushButton{\n"
"    text-align: right;\n"
"    margin-top: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 0px solid transparent;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(183, 228, 255);\n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    background-color: rgb(165, 165, 165);\n"
"    border-color: rgb(77, 77, 77);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить задачу"))
        self.label.setText(_translate("Form", "Добавить задачу"))
        self.task_line.setPlaceholderText(_translate("Form", "Добавить задачу"))
        self.label_2.setText(_translate("Form", "Дата выполнения"))
        self.cancel.setText(_translate("Form", "Отмена"))
        self.add.setText(_translate("Form", "Добавить задачу"))
