# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 404)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 800))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcome = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.welcome.setFont(font)
        self.welcome.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.welcome.setObjectName("welcome")
        self.verticalLayout.addWidget(self.welcome)
        self.main_list = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.main_list.setFont(font)
        self.main_list.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_list.setStyleSheet("QListWidget{\n"
                                     "    border: 1px solid transparent;\n"
                                     "    background-color: rgba(255, 255, 255, 0);\n"
                                     "}")
        self.main_list.setIconSize(QtCore.QSize(15, 15))
        self.main_list.setObjectName("main_list")
        self.verticalLayout.addWidget(self.main_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.add.setFont(font)
        self.add.setStyleSheet("QPushButton{\n"
                               "    text-align: left;\n"
                               "    background-color: rgba(255, 255, 255, 0);\n"
                               "    border: 0px solid transparent;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover\n"
                               "{\n"
                               "    background-color: rgb(208, 208, 208);\n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed\n"
                               "{\n"
                               "    background-color: rgb(183, 228, 255);\n"
                               "}\n"
                               "\n"
                               "QPushButton:disabled\n"
                               "{\n"
                               "    background-color: rgb(165, 165, 165);\n"
                               "    border-color: rgb(77, 77, 77);\n"
                               "    color: rgb(255, 255, 255);\n"
                               "}")
        self.add.setObjectName("add")
        self.horizontalLayout.addWidget(self.add)
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.settings.setFont(font)
        self.settings.setStyleSheet("QPushButton{\n"
                                    "    text-align: left;\n"
                                    "    \n"
                                    "    background-color: rgba(255, 255, 255, 0);\n"
                                    "    border: 0px solid transparent;\n"
                                    "    margin-left: 115px;\n"
                                    "}\n"
                                    "\n"
                                    "QAbstractButton{\n"
                                    "     qproperty-iconSize: 20px;\n"
                                    "}\n"
                                    "\n"
                                    "QAbstractButton::hover {\n"
                                    "     qproperty-iconSize: 25px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed\n"
                                    "{\n"
                                    "    background-color: rgb(183, 228, 255);\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:disabled\n"
                                    "{\n"
                                    "    background-color: rgb(165, 165, 165);\n"
                                    "    border-color: rgb(77, 77, 77);\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "}")
        self.settings.setObjectName("settings")
        self.horizontalLayout.addWidget(self.settings)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ToDo"))
        self.welcome.setText(_translate("MainWindow", "Добро\n"
                                                      "пожаловать"))
        self.add.setText(_translate("MainWindow", " Добавить список "))
        self.settings.setText(_translate("MainWindow", "Настройки"))
