# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 132)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.font_count = QtWidgets.QSpinBox(Form)
        self.font_count.setMinimum(1)
        self.font_count.setMaximum(30)
        self.font_count.setProperty("value", 14)
        self.font_count.setObjectName("font_count")
        self.horizontalLayout.addWidget(self.font_count)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setMinimum(16)
        self.spinBox.setMaximum(30)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_3.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gray = QtWidgets.QPushButton(self.groupBox)
        self.gray.setStyleSheet("background-color: rgb(169, 185, 200);")
        self.gray.setText("")
        self.gray.setObjectName("gray")
        self.horizontalLayout_4.addWidget(self.gray)
        self.pink = QtWidgets.QPushButton(self.groupBox)
        self.pink.setStyleSheet("background-color: rgb(255, 225, 245);")
        self.pink.setText("")
        self.pink.setObjectName("pink")
        self.horizontalLayout_4.addWidget(self.pink)
        self.black = QtWidgets.QPushButton(self.groupBox)
        self.black.setStyleSheet("background-color: rgb(44, 44, 44);")
        self.black.setText("")
        self.black.setObjectName("black")
        self.horizontalLayout_4.addWidget(self.black)
        self.white = QtWidgets.QPushButton(self.groupBox)
        self.white.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.white.setText("")
        self.white.setObjectName("white")
        self.horizontalLayout_4.addWidget(self.white)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.label.setText(_translate("Form", "Размер шрифта"))
        self.label_2.setText(_translate("Form", "Размер сторны иконок"))
        self.groupBox.setTitle(_translate("Form", "Цветовое оформление"))
