# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 455)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.date = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.date.setFont(font)
        self.date.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.date.setObjectName("date")
        self.verticalLayout.addWidget(self.date)
        self.list_todo = QtWidgets.QListWidget(Form)
        self.list_todo.setStyleSheet("QListWidget{\n"
                                     "    border: 1px solid transparent;\n"
                                     "    background-color: rgba(255, 255, 255, 0);\n"
                                     "}\n"
                                     "\n"
                                     "QListWidget:item{\n"
                                     "    border:None;\n"
                                     "    border-bottom: 1px solid rgb(0, 157, 255);\n"
                                     "}\n"
                                     "\n"
                                     "QListWidget:item:selected{\n"
                                     "    background-color: rgb(0, 157, 255);\n"
                                     "    color: rgb(0, 0, 0);\n"
                                     "}")
        self.list_todo.setObjectName("list_todo")
        self.verticalLayout.addWidget(self.list_todo)
        self.add = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.add.setFont(font)
        self.add.setStyleSheet("QPushButton{\n"
                               "    text-align: left;\n"
                               "    background-color: rgba(255, 255, 255, 0);\n"
                               "    border: 0px solid transparent;\n"
                               "}\n"
                               "\n"
                               "QPushButton:hover\n"
                               "{\n"
                               "    background-color: rgb(208, 208, 208);\n"
                               "}\n"
                               "\n"
                               "QPushButton:pressed\n"
                               "{\n"
                               "    background-color: rgb(183, 228, 255);\n"
                               "}\n"
                               "\n"
                               "QPushButton:disabled\n"
                               "{\n"
                               "    background-color: rgb(165, 165, 165);\n"
                               "    border-color: rgb(77, 77, 77);\n"
                               "    color: rgb(255, 255, 255);\n"
                               "}")
        self.add.setObjectName("add")
        self.verticalLayout.addWidget(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Название"))
        self.name.setText(_translate("Form", "Название"))
        self.date.setText(_translate("Form", "Пятница, 28 января"))
        self.add.setText(_translate("Form", " Добавить запись "))
